---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: HTTPRoute
      name: homebridge
    patch: |-
      - op: add
        path: /spec/hostnames/-
        value: "homebridge.dudo.dev"
