---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client  # Or your actual StorageClass
  resources:
    requests:
      storage: 1Gi
